CREATE DATABASE QUAN_LY_lOP_HOC

USE QUAN_LY_lOP_HOC

--> TẠO RA 1 TABLE TÊN LỚP
CREATE TABLE LOP (
	ID_LOP INT IDENTITY NOT NULL,
	TEN_LOP NVARCHAR(50) NOT NULL UNIQUE,
	CONSTRAINT PK_LOP PRIMARY KEY (ID_LOP)
)

INSERT INTO LOP (TEN_LOP)
VALUES 
	(N'LẬP TRÌNH'),
	(N'KHOA HỌC DỮ LIỆU'),
	(N'LỚP NHÚNG');

SELECT * FROM LOP 

--> SINH VIEEN
CREATE TABLE SINH_VIEN (
	ID_SV INT IDENTITY NOT NULL,
	TEN_SV NVARCHAR(50) NOT NULL,
	GIOI_TINH BIT NOT NULL DEFAULT 0,--> 0: NAM, 1: NỮ
	LOP INT,
	CONSTRAINT FK_SINH_VIEN_LOP FOREIGN KEY (LOP) REFERENCES LOP(ID_LOP),
	CONSTRAINT PK_SINH_VIEN PRIMARY KEY (ID_SV)
) 

-- Chèn dữ liệu cho bảng SINH_VIEN
INSERT INTO SINH_VIEN (TEN_SV, GIOI_TINH, LOP) VALUES
    (N'Nguyễn Văn A', 0, 1), -- Nam, thuộc lớp LẬP TRÌNH
    (N'Nguyễn Thị B', 1, 2), -- Nữ, thuộc lớp KHOA HỌC DỮ LIỆU
    (N'Trần Văn C', 0, 1), -- Nam, thuộc lớp LẬP TRÌNH
    (N'Lê Thị D', 1, 3), -- Nữ, thuộc lớp LỚP NHÚNG
    (N'Phạm Văn E', 0, 2), -- Nam, thuộc lớp KHOA HỌC DỮ LIỆU
    (N'Lê Thị F', 1, 1), -- Nữ, thuộc lớp LẬP TRÌNH
    (N'Trần Văn G', 0, 3), -- Nam, thuộc lớp LỚP NHÚNG
    (N'Nguyễn Thị H', 1, 2), -- Nữ, thuộc lớp KHOA HỌC DỮ LIỆU
    (N'Lê Văn I', 0, 1), -- Nam, thuộc lớp LẬP TRÌNH
    (N'Trần Thị K', 1, 3); -- Nữ, thuộc lớp LỚP NHÚNG

INSERT INTO SINH_VIEN (TEN_SV) VALUES
    (N'Nguyễn Văn Ahihi') -- Nam, thuộc lớp LẬP TRÌNH

SELECT * FROM SINH_VIEN
SELECT * FROM LOP

-- INNER JOIN: CHO PHÉP NỐI BÊN TRONG CÁC BẢN GHI CÓ GIÁ TRỊ TRÙNG KHỚP TRONG CẢ 2 BẢNG
-- LẤY RA TẤT CẢ CÁC TRƯỜNG TRONG BẢNG SINH_VIEN VÀ BẢNG LOP
SELECT * FROM SINH_VIEN
INNER JOIN LOP ON LOP.ID_LOP = SINH_VIEN.LOP

-- LEFT JOIN: CHO PHÉP NỐI TRÁI LẤY TẤT CẢ CÁC BẢN GHI TỪ BÊN TRÁI (SINH_VIEN) VÀ CÁC BẢN GHI BÊN PHẢI (LOP)
-- KẾT QUẢ LÀ NULL Ở PHÍA BÊN PHẢI NẾU KHÔNG CÓ DỮ LIỆU TRÙNG KHỚP
SELECT * FROM SINH_VIEN
LEFT JOIN LOP ON LOP.ID_LOP = SINH_VIEN.LOP

-- RIGHT JOIN: CHO PHÉP NỐI PHẢI LẤY TẤT CẢ CÁC BẢN GHI TỪ BÊN PHẢI (LOP) VÀ CÁC BẢN GHI TRÙNG KHỚP TỪ BẢNG BÊN TRÁI (SINH_VIEN)
-- KẾT QUẢ LÀ NULL Ở PHÍA BÊN TRÁI NẾU KHÔNG CÓ KẾT QUẢ TRÙNG KHỚP
SELECT * FROM SINH_VIEN
RIGHT JOIN LOP ON LOP.ID_LOP = SINH_VIEN.LOP

-- FULL OUTER JOIN: CHO PHÉP CHÚNG TA NỐI ĐẦY ĐỦ, SẼ TRUY XUẤT HẾT CÁC BẢN GHI KHI CÓ SỰ TRÙNG KHỚP CÁC BẢNG VỚI NHAU.
-- NẾU MÀ KHÔNG CÓ KẾT QUẢ TRÙNG KHỚP, KẾT QUẢ LÀ NULL TỪ PHÍA KHÔNG CÓ KẾT QUẢ KHỚP
SELECT * FROM SINH_VIEN
FULL OUTER JOIN LOP ON SINH_VIEN.LOP = LOP.ID_LOP


--> MUỐN LẤY RA TẤT CẢ CÁC TRƯỜNG SINH VIÊN, TRƯỜNG LỚP CÓ MÀ LỚP LÀ NULL
SELECT * FROM SINH_VIEN
LEFT JOIN LOP ON SINH_VIEN.LOP = LOP.ID_LOP
WHERE SINH_VIEN.LOP IS NULL

--> LẤY MÃ LỚP, TÊN LỚP, ĐẾM SỐ SINH VIÊN TRONG LỚP ĐÓ
--SELECT COUNT(SINH_VIEN) FROM SINH_VIEN
--RIGHT JOIN LOP ON SINH_VIEN.LOP = LOP.ID_LOP
--WHERE SINH_VIEN.LOP = LOP.ID_LOP
SELECT COUNT(*) FROM SINH_VIEN
SELECT LOP.ID_LOP, LOP.TEN_LOP, COUNT(SINH_VIEN.LOP) AS N'SĨ SỐ LỚP' FROM LOP
LEFT JOIN SINH_VIEN ON SINH_VIEN.LOP = LOP.ID_LOP
GROUP BY LOP.ID_LOP, LOP.TEN_LOP

SELECT LOP.ID_LOP, LOP.TEN_LOP, COUNT(SINH_VIEN.LOP) AS N'SĨ SỐ LỚP' FROM SINH_VIEN
RIGHT JOIN LOP ON SINH_VIEN.LOP = LOP.ID_LOP
GROUP BY LOP.ID_LOP, LOP.TEN_LOP








